name: Test

on:
  push:
  pull_request:
  schedule:
    # Every day at 18:23
    - cron: "23 18 * * *"

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        lisp: [abcl-bin, ccl-bin, cmu-bin/21e, ecl, sbcl-bin]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Let ASDF find the project
        run: mkdir ~/common-lisp; ln -s `pwd` ~/common-lisp/journal

      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh

      - name: Install latest stuff from GitHub
        run: |
          # KLUDGE: 'ros install' wants to compile things immediately
          # after downloading, but there are circular dependencies on
          # the repository level. There are no circular dependencies
          # at the ASDF level though, so let's just clone everything
          # before compiling.
          cd ~/.roswell/local-projects/
          git clone --depth 1 https://github.com/melisgl/autoload
          git clone --depth 1 https://github.com/melisgl/named-readtables
          git clone --depth 1 https://github.com/melisgl/dref
          git clone --depth 1 https://github.com/melisgl/mgl-pax
          git clone --depth 1 https://github.com/melisgl/try

      - name: Run tests
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          ros run -e '(ql:quickload :journal)' -q
          ./test/test.sh $LISP
